/* AUTO-GENERATED by gl_codegen.py — DO NOT EDIT */
#ifndef GEN_GL_CLIENT_H
#define GEN_GL_CLIENT_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Returns our wrapper function pointer for the given GL function name,
 * or nullptr if the name is not handled by this generated layer.
 */
void *gl_get_function_pointer(const char *name);

#ifdef __cplusplus
}
#endif

#endif /* GEN_GL_CLIENT_H */
