/* AUTO-GENERATED by gl_codegen.py — DO NOT EDIT */
#ifndef GEN_GL_SERVER_H
#define GEN_GL_SERVER_H

#include "rpc.h"

/**
 * Dispatch a batch payload or a synchronous RPC call for the given GL
 * function ID.  Returns 0 on success, -1 on error.
 *
 * For batch (void/scalar) commands, payload/payload_size hold the
 * serialised argument bytes.  For sync commands, payload is null and
 * arguments are read directly from conn.
 */
int gl_dispatch(conn_t *conn, int func_id,
                const uint8_t *payload, size_t payload_size);

#endif /* GEN_GL_SERVER_H */
